# Generated by Django 2.2.12 on 2021-01-22 16:11

from django.db import migrations, models
import userpost.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PassportDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_img', models.ImageField(blank=True, null=True, upload_to=userpost.models.upload_location)),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passport danniylar',
            },
        ),
    ]
