# Generated by Django 3.1.5 on 2021-01-25 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportdatamodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
